#!groovy

import com.sap.piper.Utils

/**
 *	Copyright (c) 2017 SAP SE or an SAP affiliate company.  All rights reserved.
 *
 *	This software is the confidential and proprietary information of SAP
 *	("Confidential Information"). You shall not disclose such Confidential
 *	Information and shall use it only in accordance with the terms of the
 *	license agreement you entered into with SAP.
*/

@Library('oliver-piper-library-os@neoDeploy') _

node() {
  //Global variables:
  APP_PATH = 'src'
  SRC = "${WORKSPACE}/${APP_PATH}"

  stage("Clone sources and setup environment"){
    deleteDir()
    dir(SRC) {
      checkout([$class: 'GitSCM', 
                branches: [[name: params.GIT_BRANCH]], 
                doGenerateSubmoduleConfigurations: false, 
                extensions: [[$class: 'RelativeTargetDirectory', relativeTargetDir: APP_PATH]], 
                submoduleCfg: [], 
                userRemoteConfigs: [[url: params.GIT_URL]]])
    }
    commonPipelineEnvironment.setConfigProperties([ DEPLOY_HOST: 'hanatrial.ondemand.com',
                                                    CI_DEPLOY_ACCOUNT: 'p1942792592trial',
                                                    neoCredentialsId: 'cp-P1942792592'])
    MTA_JAR_LOCATION = '/opt/mta'
    NEO_HOME = '/usr/local/tools/neo-java-web-sdk'
    proxy = commonPipelineEnvironment.getConfigProperty('proxy') ?: ''
    httpsProxy = commonPipelineEnvironment.getConfigProperty('httpsProxy') ?: ''
  }

  stage("Build Fiori App"){
    dir(SRC){
      withEnv(["http_proxy=${proxy}", "https_proxy=${httpsProxy}"]) {
        MTAR_FILE_PATH = mtaBuild mtaJarLocation: MTA_JAR_LOCATION, buildTarget: 'NEO'
      }
    }
  }
  
  stage("Deploy Fiori App"){
    dir(SRC){
      withEnv(["http_proxy=${proxy}", "https_proxy=${httpsProxy}"]) {
        neoDeploy script: this, neoHome: NEO_HOME, archivePath: MTAR_FILE_PATH
      }
    }
  }
}


